<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>QSLink</RootNamespace>
    <AssemblyName>QSLink</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Programs\**\*" />
  </ItemGroup>

</Project>
