name: Build QShell Binary

on:
  workflow_dispatch:
    inputs:
      build_target:
        type: choice
        description: "编译目标"
        required: true
        default: QSBox
        options:
          - QSBox
          - QSLink
          - QSBox + QSLink

jobs:
  build-qsbox:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27d
          add-to-path: true
    
      - name: Setup Rust Android target
        run: |
          rustup target add aarch64-linux-android
        
          # 验证工具链
          rustc --print target-list | grep android || echo "Android targets not listed"

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v6
        with:
        dotnet-version: '8.0.424'

      - name: Build QSBox
        if: ${{ github.event.inputs.build_target == 'QSBOX' }} || ${{ github.event.inputs.build_target == 'QSBOX+QSLink' }}
        run: |
          Set-Location .\tools\qsbox
          .\build.ps1

      - name: Build QSLink
        if: ${{ github.event.inputs.build_target == 'QSLink' }} || ${{ github.event.inputs.build_target == 'QSBOX+QSLink' }}
        run: |
          Set-Location .\tools\QSLink
          dotnet publish -c Release -r win-x64 --self-contained false -p:PublishSingleFile=true -o publish

      - name: Upload QSBox
        uses: actions/upload-artifact@v7
        with:
          name: QSBox
          path: Dtools\qsbox\target\aarch64-linux-android\release\qsbox

      - name: Upload QSLink
        uses: actions/upload-artifact@v7
        with:
          name: QSLink
          path: tools\QSLink\publish\QSLink.exe

